name: GitHub to Gitea Repository Sync (HTTPS Only)

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 2 * * 0'  # 每周日凌晨2点自动执行

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # 即使有失败的仓库，也继续同步其他仓库
      max-parallel: 10  # 最大并行同步数量
      matrix:
        repo:
          # GitHub到Gitea的映射配置
          - { 
              src: "github/xiebaiyuan", 
              dst: "gitea/xiebaiyuan",  # 格式固定为：gitea/用户名
              account_type: "user",
              static_list: ""  # 留空表示同步所有仓库
            }
          # 可以添加更多仓库配置
          # - { src: "github/another-org", dst: "gitea/another-org-name", account_type: "org" }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror repository from GitHub to Gitea (HTTPS方式)
        uses: Yikun/hub-mirror-action@master
        env:
          # 只有服务器URL是真正需要保护的敏感信息
          GITEA_HOSTNAME: "${{ secrets.GITEA_SERVER_URL }}"  # 例如: https://code.aa.com:8443
        with:
          src: ${{ matrix.repo.src }}
          dst: ${{ matrix.repo.dst }}
          dst_key: ${{ secrets.GITEA_PRIVATE_KEY }}  # 即使是HTTPS方式也需要提供这个参数
          dst_token: ${{ secrets.GITEA_TOKEN }}
          account_type: ${{ matrix.repo.account_type }}
          clone_style: "https"  # 使用HTTPS克隆
          timeout: "2h"  # 超时时间设置为2小时，避免大型仓库同步中断
          debug: true
          force_update: false  # 改为false，这样只会同步有变化的分支
          cache_path: "/github/workspace/hub-mirror-cache"  # 缓存路径
          static_list: "${{ matrix.repo.static_list }}"  # 可选：指定需要同步的仓库列表
          black_list: ""  # 可选：指定不需要同步的仓库黑名单
          white_list: ""  # 可选：指定只同步的仓库白名单
          # 更多配置选项请参考官方文档
          # https://github.com/Yikun/hub-mirror-action

      - name: Cleanup cache
        if: always()
        run: |
          rm -rf /github/workspace/hub-mirror-cache